{% set version = "0.8.5" %}

package:
  name: impactutils
  version: {{ version }}

source:
  url: https://github.com/usgs/earthquake-impact-utils/archive/{{ version }}.tar.gz
  sha256: 938d033b6fa2984d919de2c39b2a4846b44d23fa6092e9b6aef13660c018d9c0

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - beautifulsoup4 >=4.4.0
    - cartopy >=0.14.0
    - fiona >=1.6.0
    - h5py >=2.2
    - matplotlib <2.0
    - numpy >=1.0
    - pandas >=0.8.1
    - paramiko >=1.15.2
    - pycrypto >=2.6.1
    - shapely >=1.5.11

test:

  imports:
    - impactutils

about:
  home: https://github.com/usgs/earthquake-impact-utils
  license: Public Domain
  summary: 'Utility library for USGS earthquake applications.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
