{% set version = "0.8.31" %}

package:
  name: impactutils
  version: {{ version }}

source:
  url: https://github.com/usgs/earthquake-impact-utils/archive/{{ version }}.tar.gz
  sha256: b0bbad6ff2fd10e802dd0e64f2848dbf5ec22bcca6d153865982cc2e9f555a0e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - beautifulsoup4
    - cartopy
    - defusedxml
    - fiona
    - h5py
    - matplotlib
    - numpy
    - pandas
    - paramiko
    - pycrypto
    - pyproj
    - shapely

test:
  imports:
    - impactutils

about:
  home: https://github.com/usgs/earthquake-impact-utils
  license: CC-PDDC
  summary: Utility library for USGS earthquake applications.
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - emthompson-usgs
    - cbworden
