{% set version = "0.8.11" %}

package:
  name: impactutils
  version: {{ version }}

source:
  url: https://github.com/usgs/earthquake-impact-utils/archive/{{ version }}.tar.gz
  sha256: c99002c6e704c511f993a6c658ceef78ad25f8dc55d4a6a826274e601bd669b3

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - beautifulsoup4
    - cartopy
    - fiona
    - h5py
    - matplotlib
    - numpy
    - pandas
    - paramiko
    - pycrypto
    - shapely

test:

  imports:
    - impactutils

about:
  home: https://github.com/usgs/earthquake-impact-utils
  license: Public Domain
  summary: 'Utility library for USGS earthquake applications.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
