{% set version = "0.8.12" %}

package:
  name: impactutils
  version: {{ version }}

source:
  url: https://github.com/usgs/earthquake-impact-utils/archive/{{ version }}.tar.gz
  sha256: 12f38e4a88c4a70a943f98a79297e4e0de0ed071ba0f46fcb9731db4146d9535

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - beautifulsoup4
    - cartopy
    - fiona
    - h5py
    - matplotlib
    - numpy
    - pandas
    - paramiko
    - pycrypto
    - shapely

test:
  imports:
    - impactutils

about:
  home: https://github.com/usgs/earthquake-impact-utils
  license: Public Domain
  summary: 'Utility library for USGS earthquake applications.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - emthompson-usgs
    - cbworden
