{% set version = "0.8.2" %}

package:
  name: impactutils
  version: {{ version }}

source:
  url: https://github.com/usgs/earthquake-impact-utils/archive/{{ version }}.tar.gz
  sha256: 29f0e3d4584cf78b9a741cbb0b4c38bd7f1f9d0af05087d13df525f42704924a

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - beautifulsoup4 >=4.4.0
    - cartopy >=0.14.0
    - fiona >=1.6.0
    - h5py >=2.2
    - matplotlib <2.0
    - numpy >=1.0
    - pandas >=0.8.1
    - paramiko >=1.15.2
    - pycrypto >=2.6.1
    - shapely >=1.5.11

test:

  imports:
    - impactutils

about:
  home: https://github.com/usgs/earthquake-impact-utils
  license: Public Domain
  summary: 'Utility library for USGS earthquake applications.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
