{% set version = "0.8.27" %}

package:
  name: impactutils
  version: {{ version }}

source:
  url: https://github.com/usgs/earthquake-impact-utils/archive/{{ version }}.tar.gz
  sha256: 44b374294905b7cb23ab047d25857f5d9c11b9b805505c7c189c9ce087173818

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - beautifulsoup4
    - cartopy
    - defusedxml
    - fiona
    - h5py
    - matplotlib
    - numpy
    - pandas
    - paramiko
    - pycrypto
    - pyproj
    - shapely

test:
  imports:
    - impactutils

about:
  home: https://github.com/usgs/earthquake-impact-utils
  license: Public Domain
  summary: Utility library for USGS earthquake applications.
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - emthompson-usgs
    - cbworden
