{% set version = "0.8" %}

package:
  name: impactutils
  version: {{ version }}

source:
  url: https://github.com/usgs/earthquake-impact-utils/archive/{{ version }}.tar.gz
  sha256: 585a0b8bde7a02cd3835f3a9b994975b327ba8b3d5687204be0db757a279a2a8

build:
  number: 0
  skip: True  # [py27]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - beautifulsoup4 >=4.4.0
    - cartopy >=0.14.0
    - fiona >=1.6.0
    - h5py >=2.2
    - matplotlib <2.0
    - numpy >=1.0
    - jupyter
    - pandas >=0.8.1
    - paramiko >=1.15.2
    - pycrypto >=2.6.1
    - shapely >=1.5.11

test:

  imports:
    - impactutils

about:
  home: https://github.com/usgs/earthquake-impact-utils
  license: Public Domain
  summary: 'Utility library for USGS earthquake applications.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
