{% set version = "0.8.21" %}

package:
  name: impactutils
  version: {{ version }}

source:
  url: https://github.com/usgs/earthquake-impact-utils/archive/{{ version }}.tar.gz
  sha256: ba7b0194b234c95425de044624afc0091997c6109d35737ea5da2cad801aa5ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - beautifulsoup4
    - cartopy
    - fiona
    - h5py
    - matplotlib
    - numpy
    - pandas
    - paramiko
    - pycrypto
    - shapely

test:
  imports:
    - impactutils

about:
  home: https://github.com/usgs/earthquake-impact-utils
  license: Public Domain
  summary: Utility library for USGS earthquake applications.
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - emthompson-usgs
    - cbworden
