travis:
  secure:
    BINSTAR_TOKEN: EY40H643xo5DWR38pMBEOTt0Z3CWWfWP9pfRADxUC9itlOPWXasPmzYiQaux8NmG9yOSFwEX+JlbYuFGagz/5Ur2dZeYqJIfM6O+r5UOz+hnmZ9cNbb0Lywsc5CnVfeqUOIMJm61xHP1ZGK744fj8oZ1dtyarkm0nV4pmHQvozu56gFHxfaJSIZDbvMfPCn/FoG+uZv4OoNLYzqHK5AVkFkDDrUX+qmtbARxHizHYYCC9xhlB1Wad8NLbPwc84g6WUHfttJLHMxSEUgIPsZdAZPGZBSgseVGV4T7sl7DvPHTyk+erDGESEytNrzHr1nw3mz3Jo2wEsgO5YfHuGv+dZ9geh6gdWHRJ6TZaeKpkpRrFaVTWL3fM5CDQMZzDP/PC6ttizeqZxMSXn/PqhwXr11PbLSDaeETA3aRj+HRLNVlR2N++ZWhmMC5wD6n6LuBsT8BHn3LBHsQduCtuT0x2/VjjaroaFiG6dytc3M9J1jyNZX1EZfD6MZKBVLRECwA7ixfBJFJ1sALTdy3GLbZkX/1HkcHQmOU3lsVmBz+pDWHxCkwZKiBEAEMjPvmSk/po1/qlRgG3IAft/xtsa+RGwYnJC+R24+xp+mlHzaV+D/unKeSh0unFoA94ba45LyvchfNFbdRYFivjxj9WMHc8TE0bVEGW1oygp4LbJHOeu4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
