travis:
  secure:
    BINSTAR_TOKEN: IJUq3XOdUDNZeCFsyUlQoWlju7LsB3O/kRA6ByKyEYd2GRyac4fo8tB1vt7b5G10T4z98euhfPGYYljJZhf4Hj6dihfS4w3nnH+XxK1q+zSKFP5movpd4IPx9PqKvHPYgoHXww2x/dT9qA0Oy5AR4XISuGZ9pjajNazXymTiA+6uvPRAXcUXEGyHpR5nNmQMllQ8QpNDblkkmTsMk61NKlXuy5f3ECnNb71DUsM9R6ddAHoJeRWRH00DAcgCPXqARuIZg0ReYPbqNHI0cKvx3Qblvnn69KunCErOI5tu/Rf/laFJLBKZT5zGTEc4H9+KAhqjIJVKLb01/zXnV79nWU2aqBZzsgc++ylL1U0CSGPeebD/npdyYl1Kd1IZVj/6U+eogXkGbAJZDrEXyL+07lUqfdbdaKeXk8nCzqS9bQLV2SDxUYeBWKa4n8WCrZo+zvSr/6h5+4uolwogmlRDcW8i2PWEaPaKeuMsNsM70iXeUbVsUS93w4saRbd1TX+MVEUAnZek3ef6TIkDv93avT4ByuQbQKxGuy9Eyg9UKbbvH7iwMOTKDTEwRz32Xac3d851I34pc8ogmKM9eaJebiGrcSVyKCV4TnEYbkcxhZtR/94OdMZP+0QM0/3dbbrpNLLxtX4FyFYU5d3Kfk2M3ygLyf0CdJpaChY8ADmhIGg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
